# Generated by Django 5.0.3 on 2024-03-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='User id'),
            preserve_default=False,
        ),
    ]
