# Generated by Django 5.0.3 on 2024-03-28 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_alter_task_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user_id_aboba',
        ),
    ]
