# Generated by Django 5.0.3 on 2024-03-28 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_rename_user_id_task_user_id_aboba'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user_id_aboba',
            new_name='user',
        ),
    ]
