# Generated by Django 5.0.3 on 2024-03-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_rename_user_id_aboba_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
