# Generated by Django 5.0.3 on 2024-04-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desctiption',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
